POPSIZE: 32
NN_LAYERS: 2
NUM_HIDDEN_LAYERS: 1
EVO_ALG: "OpenES"
LR: 0.005
NUM_ENVS: 64
NUM_STEPS: 128
TOTAL_TIMESTEPS: 10000000
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 8
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ACTIVATION: "nonlinear"
ENV_NAME: "Breakout-MinAtar"
ANNEAL_LR: true
SPARSE_ACTIVATION: 0
INNER_ACTIVATION: "tanh"
NUM_GENERATIONS: 150
NUM_ROLLOUTS: 2
NUM_NODES: 10
SEED: 20
LOG: 0
WANDB_MODE: "online"
PROJECT: ""